### ISSUE TITLE
[QZ0] Problems with pushing files into my Github repository

### ISSUE THREAD

**Issue by ghost** [emory-courses/dsa-java#17] opened 2020-08-24 15:39 UTC
Hello everyone. I have run into a problem where my pushed files are not shown in my repository.

![Screen Shot 2020-08-24 at 11 31 49](https://user-images.githubusercontent.com/69917917/91064581-6ad43480-e5fd-11ea-8a5b-5ce4d199ece6.png)

I tried to push "src" into my repository and it told me in IDE that everything was up-to-date, but I just couldn't find it on my repository page.

![Screen Shot 2020-08-24 at 11 36 23](https://user-images.githubusercontent.com/69917917/91065066-0b2a5900-e5fe-11ea-856a-5062442a465b.png)

I also tried to open the files in Github but it told me that it won't open in browser because it couldn't get the last version.

I'm so confused, please help.

**Comment by jdchoi77** [comment] 2020-08-24 15:41
@kxiao02 please make sure you "pushed" after making "commits" which are two separate steps.

**Comment by kxiao02** [comment] 2020-08-24 15:47
> @kxiao02 please make sure you "pushed" after making "commits" which are two separate steps.

Yes, I have pushed the whole project and it tells me that everything is up-to-date. I think the problem might be that I imported the project with the remote name 'github' instead of 'origin'?

**Comment by jdchoi77** [comment] 2020-08-24 15:51
@kxiao02 the name of the branch should be origin instead of github

**Comment by kxiao02** [comment] 2020-08-24 15:53
@jdchoi77 How can I fix that?

**Comment by jdchoi77** [comment] 2020-08-24 16:00
@kxiao02 a proper but possibly difficult way is to learn how to change a remote branch name (so much resource available for this online). An easy way is to delete your local project and repo in Github and start from scratch but this time, make sure the origin branch is setup properly.

**Comment by kxiao02** [comment] 2020-08-24 16:19
@jdchoi77 Ok! Thank you so much :)

**Comment by lujiaying** [comment] 2020-08-25 02:18
@kxiao02 Could you share your solution to benefit the class?

Besides, if this issue has been solved, please close it.

**Comment by kxiao02** [comment] 2020-08-25 02:23
@lujiaying Sorry I still haven't solve the problem. There was some problem with my romote brach in the first place or I wouldn't be using 'github' instead. So simply deleting everything won't work. Maybe I'll come up with a solution to this problem tomorrow.

**Comment by lujiaying** [comment] 2020-08-25 02:27
Got it. No worry to rush at all.

Same as Dr. Choi's suggestion, the easiest way is to delete both **local** codebase in your laptop and **remote** repository in Github to get a clean starting point. And re-do the whole process from scratch.

**Comment by kxiao02** [comment] 2020-08-25 02:32
@lujiaying But the problem is that my remote named 'origin' leads to a 404 page that exist even if a repository is absent, and I have no clue how to get rid of it. Will deleting the local project also delete the remote, too?

**Comment by kxiao02** [comment] 2020-08-25 02:34
@lujiaying Maybe I'll just re-do the whole process lol.

**Comment by lujiaying** [comment] 2020-08-25 02:43
I would recommend maybe to study some core concepts "Github Remote repository vs local repository", "Github Branch". 
"Origin" is the branch name, and if you previously push your local branch into remote `github` branch, you would still able to push your local branch into remote `origin` branch. 

After `origin` branch is pushed successfully, you can safely delete `github` branch.

**Comment by kxiao02** [comment] 2020-08-26 22:00
Sorry for replying so late. I have deleted my local project as well as my github account and started over. Everything is fine now. @lujiaying Could you help me close this issue? I have no access now.

**Closed** 2020-08-27 01:04 UTC
Labels: quiz
